version: "3"

services:
  ice_house:
    build: .
    container_name: ice_house
    depends_on:
      - verdaccio
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio-config.yml:/verdaccio/conf/config.yaml"
      - "verdaccio_storage:/verdaccio/storage"

volumes:
  verdaccio_storage:

networks:
  default:
