version: "3"

services:
  verdaccio:
    container_name: verdaccio
    build: .
    ports:
      - "4873:4873"
    volumes:
      - "verdaccio_storage:/verdaccio/storage"

volumes:
  verdaccio_storage:
